@tool
class_name GameplayTagCodeGenerator
extends RefCounted

const GENERATED_CLASS_NAME: String = "GameplayTagIds"
const GENERATED_FILE_MARKER: String = (
	"# Generated by the Gameplay Tags addon " + "from the central tag database."
)


static func save_tag_ids(
	database: GameplayTagDatabase, output_path: String = GameplayTagUtils.DEFAULT_TAG_IDS_PATH
) -> Error:
	var clean_path: String = output_path.strip_edges()
	if clean_path.is_empty():
		return ERR_INVALID_PARAMETER

	var collisions: Array[Dictionary] = get_constant_name_collisions(database)
	if not collisions.is_empty():
		push_error(_format_constant_name_collisions(collisions))
		return ERR_ALREADY_EXISTS

	var ownership_error: Error = _validate_existing_output(clean_path)
	if ownership_error != OK:
		return ownership_error

	var generated_source: String = build_tag_ids_source(database)
	if (
		FileAccess.file_exists(clean_path)
		and FileAccess.get_file_as_string(clean_path) == generated_source
	):
		# Byte-identical output needs no write, so saving without changes keeps the
		# generated script's modification time stable for build systems and editors.
		return OK

	var directory_error: Error = GameplayTagUtils.ensure_parent_directory(clean_path)
	if directory_error != OK:
		return directory_error

	var file: FileAccess = FileAccess.open(clean_path, FileAccess.WRITE)
	if file == null:
		return FileAccess.get_open_error()

	file.store_string(generated_source)
	file.close()
	return OK


static func _validate_existing_output(path: String) -> Error:
	if not FileAccess.file_exists(path):
		return OK

	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		return FileAccess.get_open_error()
	var existing_source: String = file.get_as_text()
	file.close()

	var source_lines: PackedStringArray = existing_source.split("\n")
	var expected_class_declaration: String = "class_name %s" % GENERATED_CLASS_NAME
	if source_lines.has(GENERATED_FILE_MARKER) and source_lines.has(expected_class_declaration):
		return OK

	push_error(
		"Refusing to overwrite a script not generated by the Gameplay Tags addon at: %s" % path
	)
	return ERR_FILE_UNRECOGNIZED


static func build_tag_ids_source(database: GameplayTagDatabase) -> String:
	var collisions: Array[Dictionary] = get_constant_name_collisions(database)
	if not collisions.is_empty():
		push_error(_format_constant_name_collisions(collisions))
		return ""
	var entries: Array[Dictionary] = _get_constant_entries(database)
	var lines: Array[String] = [
		"@tool",
		"class_name %s" % GENERATED_CLASS_NAME,
		"extends RefCounted",
		"",
		GENERATED_FILE_MARKER,
		"# Do not edit by hand. Edit tags in the Gameplay Tags dock instead.",
		"",
	]

	if entries.is_empty():
		lines.append("# No gameplay tags are registered yet.")
	else:
		for entry in entries:
			lines.append(
				(
					'const %s: StringName = &"%s"'
					% [String(entry["name"]), _escape_tag_literal(entry["tag"])]
				)
			)

	lines.append("")
	lines.append("")
	lines.append("static func all() -> Array[StringName]:")
	if entries.is_empty():
		lines.append("\treturn []")
	else:
		lines.append("\treturn [")
		for entry in entries:
			lines.append("\t\t%s," % String(entry["name"]))
		lines.append("\t]")
	lines.append("")
	return "\n".join(lines)


static func refresh_editor_filesystem() -> void:
	if not Engine.is_editor_hint():
		return
	var filesystem: EditorFileSystem = EditorInterface.get_resource_filesystem()
	if filesystem != null:
		filesystem.call_deferred("scan")


static func get_constant_name_collisions(
	database: GameplayTagDatabase,
) -> Array[Dictionary]:
	var tags_by_name: Dictionary[String, Array] = {}
	if database == null:
		return []

	for tag in database.get_all_tags():
		var constant_name: String = _constant_base_name_for_tag(tag)
		var mapped_tags: Array[StringName] = []
		if tags_by_name.has(constant_name):
			mapped_tags = tags_by_name[constant_name]
		mapped_tags.append(tag)
		tags_by_name[constant_name] = mapped_tags

	var constant_names: Array[String] = []
	for constant_name in tags_by_name:
		constant_names.append(constant_name)
	constant_names.sort()
	var collisions: Array[Dictionary] = []
	for constant_name in constant_names:
		var mapped_tags: Array[StringName] = tags_by_name[constant_name]
		if mapped_tags.size() > 1:
			collisions.append({"name": constant_name, "tags": mapped_tags})
	return collisions


static func _get_constant_entries(database: GameplayTagDatabase) -> Array[Dictionary]:
	var entries: Array[Dictionary] = []
	if database == null:
		return entries

	for tag in database.get_all_tags():
		(
			entries
			. append(
				{
					"name": _constant_base_name_for_tag(tag),
					"tag": tag,
				}
			)
		)
	return entries


## Returns the generated constant name for [param raw_tag], before any collision
## suffixing. Lets the reference index map a `GameplayTagIds.` use back to its tag.
static func get_constant_name_for_tag(raw_tag: StringName) -> String:
	return _constant_base_name_for_tag(raw_tag)


static func _constant_base_name_for_tag(raw_tag: StringName) -> String:
	var tag_text: String = String(raw_tag)
	var constant_name: String = ""
	for index in range(tag_text.length()):
		var character: String = tag_text.substr(index, 1)
		if _is_ascii_letter_or_digit(character):
			constant_name += character.to_upper()
		else:
			constant_name += "_"

	while constant_name.contains("__"):
		constant_name = constant_name.replace("__", "_")
	constant_name = constant_name.trim_prefix("_").trim_suffix("_")
	if constant_name.is_empty():
		return "TAG"
	if _is_ascii_digit(constant_name.substr(0, 1)):
		return "TAG_%s" % constant_name
	return constant_name


static func _escape_tag_literal(raw_tag: StringName) -> String:
	return String(raw_tag).replace("\\", "\\\\").replace('"', '\\"')


static func _format_constant_name_collisions(collisions: Array[Dictionary]) -> String:
	var details: Array[String] = []
	for collision in collisions:
		var tag_names: Array[String] = []
		for tag in collision["tags"]:
			tag_names.append(String(tag))
		details.append("%s: %s" % [String(collision["name"]), ", ".join(tag_names)])
	return (
		"Cannot generate GameplayTagIds because tag names map to the same constant: %s"
		% "; ".join(details)
	)


static func _is_ascii_letter_or_digit(character: String) -> bool:
	if character.length() != 1:
		return false
	var code: int = character.unicode_at(0)
	return _is_ascii_digit_code(code) or (code >= 65 and code <= 90) or (code >= 97 and code <= 122)


static func _is_ascii_digit(character: String) -> bool:
	if character.length() != 1:
		return false
	return _is_ascii_digit_code(character.unicode_at(0))


static func _is_ascii_digit_code(code: int) -> bool:
	return code >= 48 and code <= 57
