@tool
extends RefCounted

const DEFAULT_TAG_IDS_PATH := "res://gameplay_tag_ids.gd"
const GENERATED_CLASS_NAME := "GameplayTagIds"


static func save_tag_ids(
	database: GameplayTagDatabase, output_path: String = DEFAULT_TAG_IDS_PATH
) -> Error:
	var clean_path := output_path.strip_edges()
	if clean_path.is_empty():
		return ERR_INVALID_PARAMETER

	var directory_error := _ensure_directory(clean_path)
	if directory_error != OK:
		return directory_error

	var file := FileAccess.open(clean_path, FileAccess.WRITE)
	if file == null:
		return FileAccess.get_open_error()

	file.store_string(build_tag_ids_source(database))
	return OK


static func build_tag_ids_source(database: GameplayTagDatabase) -> String:
	var entries := _get_constant_entries(database)
	var lines: Array[String] = [
		"@tool",
		"class_name %s" % GENERATED_CLASS_NAME,
		"extends RefCounted",
		"",
		"# Generated by the Gameplay Tags addon from the central tag database.",
		"# Do not edit by hand. Edit tags in the Gameplay Tags dock instead.",
		"",
	]

	if entries.is_empty():
		lines.append("# No gameplay tags are registered yet.")
	else:
		for entry in entries:
			lines.append(
				'const %s := &"%s"' % [String(entry["name"]), _escape_tag_literal(entry["tag"])]
			)

	lines.append("")
	lines.append("static func all() -> Array[StringName]:")
	if entries.is_empty():
		lines.append("\treturn []")
	else:
		lines.append("\treturn [")
		for entry in entries:
			lines.append("\t\t%s," % String(entry["name"]))
		lines.append("\t]")
	lines.append("")
	return "\n".join(lines)


static func refresh_editor_filesystem() -> void:
	if not Engine.is_editor_hint():
		return
	var filesystem := EditorInterface.get_resource_filesystem()
	if filesystem != null:
		filesystem.call_deferred("scan")


static func _get_constant_entries(database: GameplayTagDatabase) -> Array[Dictionary]:
	var entries: Array[Dictionary] = []
	if database == null:
		return entries

	var used_names := {}
	for tag in database.get_all_tags():
		(
			entries
			. append(
				{
					"name": _constant_name_for_tag(tag, used_names),
					"tag": GameplayTagDatabase.normalize_tag(tag),
				}
			)
		)
	return entries


static func _constant_name_for_tag(raw_tag: Variant, used_names: Dictionary) -> String:
	var tag_text := String(GameplayTagDatabase.normalize_tag(raw_tag))
	var constant_name := ""
	for index in range(tag_text.length()):
		var character := tag_text.substr(index, 1)
		if _is_ascii_letter_or_digit(character):
			constant_name += character.to_upper()
		else:
			constant_name += "_"

	while constant_name.contains("__"):
		constant_name = constant_name.replace("__", "_")
	constant_name = constant_name.trim_prefix("_").trim_suffix("_")

	if constant_name.is_empty():
		constant_name = "TAG"
	if _is_ascii_digit(constant_name.substr(0, 1)):
		constant_name = "TAG_%s" % constant_name

	var base_name := constant_name
	var suffix := 2
	while used_names.has(constant_name):
		constant_name = "%s_%d" % [base_name, suffix]
		suffix += 1

	used_names[constant_name] = true
	return constant_name


static func _escape_tag_literal(raw_tag: Variant) -> String:
	return String(GameplayTagDatabase.normalize_tag(raw_tag)).replace("\\", "\\\\").replace(
		'"', '\\"'
	)


static func _is_ascii_letter_or_digit(character: String) -> bool:
	if character.length() != 1:
		return false
	var code := character.unicode_at(0)
	return _is_ascii_digit_code(code) or (code >= 65 and code <= 90) or (code >= 97 and code <= 122)


static func _is_ascii_digit(character: String) -> bool:
	if character.length() != 1:
		return false
	return _is_ascii_digit_code(character.unicode_at(0))


static func _is_ascii_digit_code(code: int) -> bool:
	return code >= 48 and code <= 57


static func _ensure_directory(path: String) -> Error:
	var directory := path.get_base_dir()
	if directory.is_empty() or directory == "res://" or directory == "user://":
		return OK
	return DirAccess.make_dir_recursive_absolute(directory)
