@tool
class_name GameplayTagIds
extends RefCounted

# Generated by the Gameplay Tags addon from the central tag database.
# Do not edit by hand. Edit tags in the Gameplay Tags dock instead.

const ABILITY := &"Ability"
const ABILITY_COOLDOWN := &"Ability.Cooldown"
const DAMAGE := &"Damage"
const DAMAGE_FIRE := &"Damage.Fire"
const DAMAGE_ICE := &"Damage.Ice"
const STATE := &"State"
const STATE_INVULNERABLE := &"State.Invulnerable"
const STATE_STUNNED := &"State.Stunned"
const TEAM := &"Team"
const TEAM_ENEMY := &"Team.Enemy"
const TEAM_PLAYER := &"Team.Player"

static func all() -> Array[StringName]:
	return [
		ABILITY,
		ABILITY_COOLDOWN,
		DAMAGE,
		DAMAGE_FIRE,
		DAMAGE_ICE,
		STATE,
		STATE_INVULNERABLE,
		STATE_STUNNED,
		TEAM,
		TEAM_ENEMY,
		TEAM_PLAYER,
	]
