@tool
class_name GameplayTagIds
extends RefCounted

# Generated by the Gameplay Tags addon from the central tag database.
# Do not edit by hand. Edit tags in the Gameplay Tags dock instead.

const ABILITY: StringName = &"Ability"
const ABILITY_COOLDOWN: StringName = &"Ability.Cooldown"
const DAMAGE: StringName = &"Damage"
const DAMAGE_FIRE: StringName = &"Damage.Fire"
const DAMAGE_ICE: StringName = &"Damage.Ice"
const STATE: StringName = &"State"
const STATE_INVULNERABLE: StringName = &"State.Invulnerable"
const STATE_STUNNED: StringName = &"State.Stunned"
const TEAM: StringName = &"Team"
const TEAM_ENEMY: StringName = &"Team.Enemy"
const TEAM_PLAYER: StringName = &"Team.Player"

static func all() -> Array[StringName]:
	return [
		ABILITY,
		ABILITY_COOLDOWN,
		DAMAGE,
		DAMAGE_FIRE,
		DAMAGE_ICE,
		STATE,
		STATE_INVULNERABLE,
		STATE_STUNNED,
		TEAM,
		TEAM_ENEMY,
		TEAM_PLAYER,
	]
